
name: "Modified MeterSphere \u524D\u7AEF\u4EE3\u7801\u6821\u9A8C"
permissions:
  pull-requests: write
jobs:
  generic_handler:
    name: generic_handler
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-generic_handler.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/metersphere/metersphere', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 21
        cache: maven
        cache-dependency-path: '**/pom.xml'
        check-latest: true
    - run: touch optcd-4.txt
    - name: Build with Maven - only frontend
      run: mvn -T 1C -B package --file pom.xml -pl frontend
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-generic_handler
        path: /home/runner/inotifywait-log-generic_handler.csv
'on':
- push
- workflow_dispatch
